# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Generate new README
      run: python readme.py
    - name: Commit new README
      run: |
        git config --global user.name 'Reinout Versteeg'
        git config --global user.email 'rcw.versteeg@avans.nl'
        [[ -n $(git status -s) ]] && git commit -am "docs: update README"
        git push
    
